apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "moloch.fullname" . }}-viewer
  labels:
    app: {{ template "moloch.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    role: viewer
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "moloch.name" . }}-viewer
      labels:
        app: {{ template "moloch.name" . }}
        role: viewer
      annotations:
        networks: '[
        { "name": {{ .Values.networks.overlay | quote }} }
        { "name": {{ .Values.networks.passive | quote }} }
      ]'
    spec:
      containers:
      - name: moloch-viewer
        image: {{ .Values.images.moloch }}
        imagePullPolicy: Always
        command: ["bash","-c","echo >> search {{ template "moloch.fullname" . }}-headless.$NAMESPACE.svc.cluster.local && /data/moloch/docker-entrypoint.sh"]
        securityContext:
          capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ES_HOST
          value: data-service
        - name: NETWORK_INTERFACE
          value: {{ .Values.networks.passive }}
        - name: CLUSTER_PW
          value: {{ .Values.molochConfig.env.clusterpw }}
        - name: ADMIN_PW
          value: {{ .Values.molochConfig.env.adminpw }}
        - name: SENSOR
          value: "false"
        ports:
        - name: cport-8005
          containerPort: 8005
        resources:
          requests:
            cpu: {{ .Values.molochConfig.requests.cpu | quote }}
            memory: {{ .Values.molochConfig.requests.memory | quote }}
          limits:
            cpu: {{ .Values.molochConfig.limits.cpu | quote }}
            memory: {{ .Values.molochConfig.limits.memory | quote }}
        volumeMounts:
        - mountPath: /data/moloch/etc/config.ini
          subPath: config.ini
          name: moloch-config
      volumes:
      - name: moloch-config
        configMap:
          name: {{ template "moloch.fullname" . }}-config
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        {{ .Values.nodeSelector.viewer }} : "true"
