apiVersion: v1
kind: Service
metadata:
  name: {{ template "moloch.fullname" . }}-viewer
  namespace: default
  labels:
    app: {{ template "moloch.name" . }}
    role: viewer
spec:
  ports:
  - name: tcp-8005
    protocol: TCP
    port: 8005
    targetPort: 8005
  selector:
    app: {{ template "moloch.name" . }}
    role: viewer

